doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain\Shared\Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Shared/Entity'
                prefix: 'Domain\Shared\Entity'

            Domain\Link\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Link/Doctrine/Mapping/Entity'
                prefix: 'Domain\Link\Entity'

            Domain\Link\ValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Link/Doctrine/Mapping/ValueObject'
                prefix: 'Domain\Link\ValueObject'

            Domain\Authentication\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Authentication/Doctrine/Mapping/Entity'
                prefix: 'Domain\Authentication\Entity'

            Domain\Authentication\ValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Authentication/Doctrine/Mapping/ValueObject'
                prefix: 'Domain\Authentication\ValueObject'


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
